### ISSUE TITLE
Test des DatenbankSystems

### ISSUE THREAD

**Issue by marvinmai** [Kassensystem/Dokumentation#5]
@Nunay 
Ich hab überlegt, dass es ja vollkommen ausreicht, wenn ich nur den Datenbank-Manager, also das GUI, teste. Da sind ja alle Funktionen mit enthalten und der DatenbankService wird implizit mit getestet. Beim Test der App wird der Rest-Api-Controller mit getestet. 
Demnach hätte ich mir letztes Semester einen Haufen zu viel Arbeit gemacht.
Oder hab ich da gerade einen Denkfehler?

**Comment by Nunay** [comment]
Ne das sollte Stimmen :)
Der Rest-Api-Controller wird dann wie du gesagt hast nicht mehr direkt getestet, sondern nur noch durch die App. Aber das sollte ja eigentlich egal sein!

Und ja, sieht so aus als ob du letztes Semester ein wenig unnötige Arbeit erledigt hast! :D
